apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: ${NAMESPACE}
spec:
  ingressClassName: ${INGRESS_CLASS_NAME}
  rules:
    - host: minio.console.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-console
                port:
                  number: 9090
