<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0"/>
        <PackageReference Include="MassTransit" Version="8.*"/>
        <PackageReference Include="MassTransit.Kafka" Version="8.*"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Implementations\Infrastructure\GamificatonService.MessageBroker\GamificatonService.MessageBroker.csproj"/>
        <ProjectReference Include="..\..\Implementations\GamificatonService.Core\GamificatonService.Core.csproj"/>
        <ProjectReference Include="..\..\Implementations\Infrastructure\GamificatonService.PersistentStorage\GamificatonService.PersistentStorage.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.Test.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\.dockerignore">
          <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
