// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReviewService.PersistentStorage;

#nullable disable

namespace ReviewService.PersistentStorage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311154357_DeleteWeightFromSchema")]
    partial class DeleteWeightFromSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HrUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hr_url");

                    b.Property<string>("IconId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("icon_id");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("site_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("Name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyFlagEntity", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("flag_id");

                    b.Property<long>("ReviewsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reviews_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CompanyId", "FlagId");

                    b.HasIndex("FlagId");

                    b.HasIndex("ReviewsCount");

                    b.HasIndex("CompanyId", "ReviewsCount");

                    b.ToTable("company_flags", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("IconId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("icon_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("site_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("Status");

                    b.ToTable("company_requests", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.FlagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("flags", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.IconEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etag");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("Bucket", "ObjectKey")
                        .IsUnique();

                    b.ToTable("icons", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DislikesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislikes_count");

                    b.Property<long>("LikesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("likes_count");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Score");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.HasIndex("CompanyId", "Score");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewFlagEntity", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("flag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReviewId", "FlagId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FlagId");

                    b.ToTable("review_flags", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_text");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_type");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReasonType");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewId");

                    b.ToTable("review_reports", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewVoteEntity", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReviewId", "VoterId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Mode");

                    b.HasIndex("VoterId");

                    b.ToTable("review_votes", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.UserProfileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("IconId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("icon_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("IconId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.IconEntity", "Icon")
                        .WithMany("Companies")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyFlagEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.CompanyEntity", "Company")
                        .WithMany("CompanyFlags")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewService.PersistentStorage.Entites.FlagEntity", "Flag")
                        .WithMany("CompanyFlags")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyRequestEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.IconEntity", "Icon")
                        .WithMany("CompanyRequests")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.UserProfileEntity", "Author")
                        .WithMany("AuthoredReviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReviewService.PersistentStorage.Entites.CompanyEntity", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewFlagEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.FlagEntity", "Flag")
                        .WithMany("ReviewFlags")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReviewService.PersistentStorage.Entites.ReviewEntity", "Review")
                        .WithMany("ReviewFlags")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewReportEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.UserProfileEntity", "Reporter")
                        .WithMany("ReviewReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReviewService.PersistentStorage.Entites.ReviewEntity", "Review")
                        .WithMany("ReviewReports")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewVoteEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.ReviewEntity", "Review")
                        .WithMany("ReviewVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewService.PersistentStorage.Entites.UserProfileEntity", "Voter")
                        .WithMany("ReviewVotes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.UserProfileEntity", b =>
                {
                    b.HasOne("ReviewService.PersistentStorage.Entites.IconEntity", "Icon")
                        .WithMany("UserProfiles")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.CompanyEntity", b =>
                {
                    b.Navigation("CompanyFlags");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.FlagEntity", b =>
                {
                    b.Navigation("CompanyFlags");

                    b.Navigation("ReviewFlags");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.IconEntity", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CompanyRequests");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.ReviewEntity", b =>
                {
                    b.Navigation("ReviewFlags");

                    b.Navigation("ReviewReports");

                    b.Navigation("ReviewVotes");
                });

            modelBuilder.Entity("ReviewService.PersistentStorage.Entites.UserProfileEntity", b =>
                {
                    b.Navigation("AuthoredReviews");

                    b.Navigation("ReviewReports");

                    b.Navigation("ReviewVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
