apiVersion: v1
kind: Secret
metadata:
  name: internal-jwt-public-key
  namespace: vibecheck
type: Opaque
stringData:
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAllL3CmzE5DzdojWqBf6+
    /5njLEyfs6ONiXil98/tpC0EwB3Ahk/zmRakl8nvvsHN/dDEinYXJyY1HUtZPUc6
    qsJiEKNysh5y3eLYLXu/OgHHgDUJkQMDGU2EFR8hT1ZwVV5BcGoODuHZRmTlDCDY
    JB00JZygeiBUjITuvfmcL+tP1t0c9rwypMgOi/2cI+K+jb+YbWubl9+Ruf5y9NAo
    ab3cPFwwf04OjGnOUzHq0w06bRK94iml4UtGMtYZqDLD9R4y1r7utlTfr9V8oyZG
    h5ayb31DMWT1RtouPA8j5OMea6NK9W4hkB8UonwCx9WC29Jp8v0uZvOv00ap/I4L
    ZwIDAQAB
    -----END PUBLIC KEY-----
