global:
  postgresql:
    auth:
      postgresPassword: "postgres"
      username: "app_user"
      password: "app_password"
      database: "review_service"

architecture: standalone

primary:
  persistence:
    enabled: true
    size: 2Gi

  service:
    type: LoadBalancer
    ports:
      postgresql: 5432

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

volumePermissions:
  enabled: true

metrics:
  enabled: false