spring.application.name=GatewayService
server.port=${SERVER_PORT:8080}

gateway.services.user-service-url=${GATEWAY_SERVICES_USER_SERVICE_URL:http://localhost:9189}
gateway.services.subscription-service-url=${GATEWAY_SERVICES_SUBSCRIPTION_SERVICE_URL:http://localhost:8082}
gateway.services.review-service-url=${GATEWAY_SERVICES_REVIEW_SERVICE_URL:http://localhost:5222}
gateway.services.gamification-service-url=${GATEWAY_SERVICES_GAMIFICATION_SERVICE_URL:http://localhost:5223}
gateway.internal-token-audiences.subscription-service=subscription-service
gateway.internal-token-audiences.review-service=review-service
gateway.internal-token-audiences.gamification-service=gamification-service
gateway.proxy-http-client.connect-timeout-millis=5000
gateway.proxy-http-client.response-timeout=5s
gateway.proxy-http-client.read-timeout=5s
gateway.proxy-http-client.write-timeout=5s
gateway.tls.enabled=${GATEWAY_TLS_ENABLED:false}
gateway.tls.client-auth=${GATEWAY_TLS_CLIENT_AUTH:NONE}
gateway.tls.protocol=${GATEWAY_TLS_PROTOCOL:TLS}
gateway.tls.key-store.path=${GATEWAY_TLS_KEYSTORE_PATH:}
gateway.tls.key-store.password=${GATEWAY_TLS_KEYSTORE_PASSWORD:}
gateway.tls.key-store.type=${GATEWAY_TLS_KEYSTORE_TYPE:PKCS12}
gateway.tls.key-store.provider=${GATEWAY_TLS_KEYSTORE_PROVIDER:}
gateway.tls.key-store.key-alias=${GATEWAY_TLS_KEY_ALIAS:}
gateway.tls.key-store.key-password=${GATEWAY_TLS_KEY_PASSWORD:}
gateway.tls.trust-store.path=${GATEWAY_TLS_TRUSTSTORE_PATH:}
gateway.tls.trust-store.password=${GATEWAY_TLS_TRUSTSTORE_PASSWORD:}
gateway.tls.trust-store.type=${GATEWAY_TLS_TRUSTSTORE_TYPE:PKCS12}
gateway.tls.trust-store.provider=${GATEWAY_TLS_TRUSTSTORE_PROVIDER:}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=UserService
springdoc.swagger-ui.urls[0].url=/gateway-api-docs/user-service
springdoc.swagger-ui.urls[1].name=SubscriptionService
springdoc.swagger-ui.urls[1].url=/gateway-api-docs/subscription-service
springdoc.swagger-ui.urls[2].name=ReviewService
springdoc.swagger-ui.urls[2].url=/gateway-api-docs/review-service
springdoc.swagger-ui.urls[3].name=GamificationService
springdoc.swagger-ui.urls[3].url=/gateway-api-docs/gamification-service
