adminUser: admin
adminPassword: admin12345

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.vibecheck.svc.cluster.local
        isDefault: true
        editable: false
