architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    size: 1Gi

  service:
    type: ClusterIP
    ports:
      redis: 6379

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
