spring.application.name=SubscriptionService
server.port=9089

spring.datasource.url=jdbc:postgresql://subscription_service_api_db:5432/subscription_service_api_db
spring.datasource.username=vitalik
spring.datasource.password=huy_sosi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.data.redis.host=subscription-service-redis
spring.data.redis.port=6379